apiVersion: v1
kind: Secret
metadata:
  name: patient-secret
  namespace: patient-system
type: Opaque
stringData:
  DB_PASSWORD: secret123
  JWT_SECRET: superSecretJWT2024PatientSystem
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: secret123
  POSTGRES_DB: patientdb
