apiVersion: v1
kind: Secret
metadata:
  name: patient-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.database.password }}
  JWT_SECRET: {{ .Values.jwt.secret }}
  POSTGRES_USER: {{ .Values.database.user }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}
  POSTGRES_DB: {{ .Values.database.name }}
